[package]
name = "afire"
version = "0.2.0"
authors = ["Connor Slade <connor@connorcode.com>"]
edition = "2018"

repository = "https://github.com/Basicprogrammer10/afire"
documentation = "https://docs.rs/afire"
description = "🔥 A blazing fast web framework for Rust"
keywords = ["http", "WebFramework", "WebServer"]
categories = ["network-programming", "web-programming::http-server"]
license = "GPL-3.0"
readme = "README.md"

[lib]
name = "afire"
path = "lib/lib.rs"

[features]
default = ["panic_handler", "thread_pool", "cookies"]

# Extions
rate_limit = []
logging = []

# Default On
panic_handler = []
cookies = []
thread_pool = []

[dev-dependencies]
# Enable rate_limit and logging features for examples
afire = { path = ".", features = ["rate_limit", "logging"] }
