[package]
name = "afire"
version = "0.1.2"
authors = ["Connor Slade <connor@connorcode.com>"]
edition = "2018"

repository = "https://github.com/Basicprogrammer10/afire"
documentation = "https://docs.rs/afire"
description = "🔥 A blazeing fast web framework for Rust"
keywords = ["http", "WebFramework", "WebServer"]
categories = ["network-programming", "web-programming::http-server"]
license = "GPL-3.0"
readme = "README.md"

[lib]
name = "afire"
path = "lib/lib.rs"

[features]
default = ["rate_limit", "logging"]
rate_limit = []
logging = []
