[package]
name = "afire"
version = "0.4.1"
authors = ["Connor Slade <connor@connorcode.com>"]
edition = "2018"

repository = "https://github.com/Basicprogrammer10/afire"
documentation = "https://docs.rs/afire"
homepage = "https://connorcode.com/writing/afire"
description = "🔥 A blazing fast web framework for Rust"
keywords = ["http", "WebFramework", "WebServer"]
categories = ["network-programming", "web-programming::http-server"]
exclude = [".github/", "SocialShare.*"]
license = "GPL-3.0"
readme = "README.md"

[lib]
name = "afire"
path = "lib/lib.rs"

[features]
default = [
  "cookies",
  "panic_handler",
  "path_patterns",
  "dynamic_resize",
  "path_decode_url",
  "ignore_trailing_path_slash"
]

# Extensions
rate_limit = []
logging = []
serve_static = []

# Default On
cookies = []
panic_handler = []
path_patterns = []
dynamic_resize = []
path_decode_url = []
ignore_trailing_path_slash = []

# Other
tracing = []

[dev-dependencies]
# Enable rate_limit and logging features for examples
afire = { path = ".", features = ["rate_limit", "logging", "serve_static", "tracing"] }
