name: CI
on: [push, pull_request]
jobs:
  buildAndTest:
      strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
      runs-on: ${{ matrix.os }}
      
      steps:
        name: Build
            runs-on: ubuntu-latest
            steps:
              - uses: actions/checkout@v2

              - name: Build
                run: cargo build

          name: Test
          runs-on: ubuntu-latest
          steps:
            - name: Run Unit Tests
              run: cargo test
